# Generated by Django 2.2.7 on 2019-12-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_price', models.CharField(db_index=True, max_length=20, verbose_name='Раздел прайса')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.AlterModelOptions(
            name='priceitem',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Прайс'},
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='pricepart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manicure.PricePart', verbose_name='Раздел'),
        ),
    ]
