# Generated by Django 2.2.7 on 2019-12-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0002_auto_20191225_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manicure/static/manicure', verbose_name='Фото')),
                ('text', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Фото и текст',
                'verbose_name_plural': 'О мастере',
            },
        ),
    ]
