# Generated by Django 2.2.7 on 2020-01-20 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0006_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Моб. телефон')),
                ('message', models.TextField(max_length=250, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AlterField(
            model_name='aboutmaster',
            name='image',
            field=models.ImageField(upload_to='static', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='feedbackitem',
            name='photo',
            field=models.ImageField(upload_to='static/feedphotos', verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(db_index=True, upload_to='static/galleryphotos', verbose_name='Ссылка на фото'),
        ),
    ]
