# Generated by Django 2.2.7 on 2020-01-23 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0007_auto_20200120_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(error_messages={'invalid': 'Некорректно введена фамилия'}, max_length=25, validators=[django.core.validators.RegexValidator(regex='[A-Za-z]')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(error_messages={'invalid': 'Некорректно введено имя'}, max_length=15, validators=[django.core.validators.RegexValidator(regex='[A-Za-z]')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'Некорректно введен номер'}, max_length=17, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7, 10}$')], verbose_name='Моб. телефон'),
        ),
    ]
