# Generated by Django 2.2.7 on 2020-01-23 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0008_auto_20200123_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'Некорректно введен номер'}, max_length=17, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Моб. телефон'),
        ),
    ]
